export { Category } from "./category/Category";
export { CourseClientView, CoursesPageClientView } from "./course";
export { UniversityClientView, UniversitiesPageClientView } from "./university";
export { DynamicListingClientView } from "./dynamic-listing";
export { BlogClientView, BlogPageClientView } from "./blog";

export { default as Hero, Hero as HeroNamed } from "./Hero";
export { default as Header, Header as HeaderNamed } from "./Header";
export { default as Footer, Footer as FooterNamed } from "./Footer";
export { default as MobileBottomNav } from "./MobileBottomNav";
export { default as CoursePageClientView } from "./CoursePageClientView";
export { default as ThankYouClient } from "./ThankYouClient";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as CompareDrawerWidget } from "./CompareDrawerWidget";
export { default as CompareUniversityClientView } from "./CompareUniversityClientView";
export { default as SafeHtmlRenderer } from "./SafeHtmlRenderer";
export { ApprovalUniversityDirectory, AccreditationsView } from "./accreditations";
export { CareerExpertsSection } from "./counselor";
export { ToolsView } from "./tools";
export { Video } from "@/components/common/Video";
export { default as ModalOTP } from "./ModalOTP";
