export { UniversityClientView, UniversityClientView as UniversityDetail, default } from "./UniversityDetail";
export { default as UniversitiesPageClientView, default as UniversitiesListing } from "./UniversitiesListing";
export { default as UniversityHero } from "./UniversityHero";
export { default as UniversityHighlights, default as UniversityKeyHighlights } from "./UniversityHighlights";
export { default as UniversityAbout } from "./UniversityAbout";
export { default as UniversityWhyChoose } from "./UniversityWhyChoose";
export { default as UniversityAccreditations } from "./UniversityAccreditations";
export { default as UniversityCourses, default as UniversityCoursesSection } from "./UniversityCourses";
export { default as UniversitySampleDegree } from "./UniversitySampleDegree";
export { default as UniversityPeerUnis, default as UniversityPeerUniversities } from "./UniversityPeerUnis";
export { default as UniversityFaq } from "./UniversityFaq";
export { default as UniversityStickyNav } from "./UniversityStickyNav";
