import urllib.request

html = urllib.request.urlopen('http://localhost:4001/liverpool/').read().decode('utf-8')

checks = [
    'Online MBA',
    'Where Global Business Education Meets Leadership Excellence',
    'Liverpool Business School',
    'IIM Udaipur',
    'upGrad',
    'Three Decades of Excellence',
    'LBS–IIM U Credential Pathway',
    'Globally Recognised',
    '18 Months',
    'Download Brochure',
    '+91 7065 7777 55',
    'Admission Open',
    'online-mba-details',
    'Eligibility',
    'Bachelor’s degree +2 years of experience',
    'Duration:',
    'Faculty:',
    'Leading industry experts',
    'Level',
    'Postgraduate Degree',
    'overview',
    'enrollment-steps',
    'Executive Programme in Business Management & AI Leadership',
    'view-sample-degree',
    'Double Certification Edge',
    'courses_offered',
    'MBA in Business Analytics',
    'MBA in Finance',
    'MBA in Marketing',
    'MBA in Leadership',
    'MBA in Human Resource Management',
    'MBA in Operations and Supply Chain Management',
    'certification',
    'why-choose',
    'What Makes',
    'Liverpool Business School MBA Stand Out?',
    'how-to-apply',
    'Submit Form',
    "Expert's Counseling",
    'Choose University',
    'Online Payment',
    'Document Submit',
    'Admission Confirm',
    'faqs',
    'compare-universities',
    'Still Confused?',
    'mini-footer',
    'call_fix_image',
    'coupon-btn',
    'sticky_btn_Section',
    'new_sode_tm_logo.png',
    'liverpool_desktop_new_bg.webp',
    'liverpool_mobile_new_img.png',
    'call_icon.gif',
    'gift.gif',
    'arrow.gif',
    'IIMU Certificatee.webp',
    'IIMU Certificatee2.webp',
    'MID-2.webp',
    'Layer-36.png',
    'Layer-37.png',
    'Layer-39-1.png',
]

missing = [c for c in checks if c not in html]
print('Total checks:', len(checks))
print('Missing checks:', missing)
if not missing:
    print('ALL 62 CHECKS PASSED PERFECTLY!')
